【レビュー依頼】　「省力化コンポーネントを知る > 導入基準」の内容作成
Fintan-contents/dev-react-cs-document pull request #10
Opened 2024-08-29 10:17 UTC by RenTakemoto-10157

2024-08-29 11:53 UTC, tashxii requested changes

2024-08-29 11:53 UTC, tashxii commented on docs/know-cs-component/introduction-standard.md
> +省力化コンポーネントの導入を検討する上で役立つ指標について紹介をします。特にバックオフィス系のシステムにおいては、省力化コンポーネントの適用効果が高く、開発効率の向上が期待できます。一方で、コンシューマー向けのシステムでは適用効果が得られにくいケースが多く、慎重な評価が求められます。本章では、導入指標として省力化コンポーネントの適用効果が高い画面および適用効果が低い画面の特徴についてそれぞれ説明
文章構成がおかしいです。

1. 省力化コンポーネントの導入を検討する上で役立つ指標について紹介をします。
2. 特にバックオフィス系のシステムにおいては、省力化コンポーネントの適用効果が高く、開発効率の向上が期待できます。
3. 一方で、コンシューマー向けのシステムでは適用効果が得られにくいケースが多く、慎重な評価が求められます。
4. 本章では、導入指標として省力化コンポーネントの適用効果が高い画面および適用効果が低い画面の特徴についてそれぞれ説明をします。

1は4の意味を薄くしただけの文章で全く意味がない文章です。4があるので、4番を一番最初に持ってきます。
2と3は、最初に読んで、なぜ？という疑問しかわきませんでした。理由がないのと語順がおかしいです。


「本章では、導入指標として省力化コンポーネントの適用効果が高い画面および適用効果が低い画面の特徴についてそれぞれ説明をします。

省力化コンポーネントは、単調なデザインで適用効果の高い画面が多くなるようなバックオフィスのシステムでは、特に開発効率の向上が期待できます。逆に、多様なデザインが求められ適用効果の低い画面が多くなるようなコンシューマー向けシステムでは慎重な検討や評価が必要となります。」

（最初に高い画面、低い画面をあげて、理由を記述→高い画面の割合が多い→例としてバックオフィス、理由を記述→低い画面の割合→例としてコンシューマという構成にしています）

2024-08-29 11:53 UTC, tashxii commented on docs/know-cs-component/introduction-standard.md
> +例として、バックオフィス系のシステムでは、その効果が特に発揮されやすいです。その理由は、画面項目が多く、バリデーションや API の呼び出しが頻繁に行われる場合でも、コード量を抑えつつ高い保守性を維持できるからです。さらに、バックオフィス系システムではこだわったデザインや複雑な画面配置を必要としないため、自動レイアウト機能を活用しやすいという特徴もあります。
「バックオフィス系のシステム」が2回出ており冗長です。
「適用効果の高い画面が多いほど、省略化コンポーネントの効果は高くなります。例として、バックオフィス系のシステムでは、画面項目の多い画面が多数ある、API呼び出しはボタンのみでも良い、デザインが単調でも許容され自動レイアウト機能を活用できる、などの理由で効果が高い傾向があります。」

2024-08-29 11:53 UTC, tashxii commented on docs/know-cs-component/introduction-standard.md
> +例として、コンシューマー向けのシステムでは効果を発揮しづらいです。視覚的情報を多く提供する場合には、図表や画像が多くなる可能性があり、導入による効果が低くなります。また、動的に変化する入力フォームに対応できないことや多様なデザインが求められる場合にも省力化コンポーネントは活かしづらくなります。
説明と総括の内容が同じ表現で被っています。
簡潔に、「上記の条件に該当するような画面が多くなると、導入の効果が薄くなります。例として、デザインの多様が求められるコンシューマー向けのシステムでは適用効果が低い画面が多くなる傾向があります。」でよいでしょう。

2024-08-30 04:26 UTC, RenTakemoto-10157 commented
タイトル、ファイル名が「導入基準」のままになっていたため「導入指標」に修正しました。

2024-08-30 08:36 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-standard.md
> +例として、コンシューマー向けのシステムでは効果を発揮しづらいです。視覚的情報を多く提供する場合には、図表や画像が多くなる可能性があり、導入による効果が低くなります。また、動的に変化する入力フォームに対応できないことや多様なデザインが求められる場合にも省力化コンポーネントは活かしづらくなります。
上記の文言に修正しました。

2024-08-30 08:37 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-standard.md
> +例として、バックオフィス系のシステムでは、その効果が特に発揮されやすいです。その理由は、画面項目が多く、バリデーションや API の呼び出しが頻繁に行われる場合でも、コード量を抑えつつ高い保守性を維持できるからです。さらに、バックオフィス系システムではこだわったデザインや複雑な画面配置を必要としないため、自動レイアウト機能を活用しやすいという特徴もあります。
上記の文言に修正しました。

2024-08-30 09:15 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-standard.md
> +省力化コンポーネントの導入を検討する上で役立つ指標について紹介をします。特にバックオフィス系のシステムにおいては、省力化コンポーネントの適用効果が高く、開発効率の向上が期待できます。一方で、コンシューマー向けのシステムでは適用効果が得られにくいケースが多く、慎重な評価が求められます。本章では、導入指標として省力化コンポーネントの適用効果が高い画面および適用効果が低い画面の特徴についてそれぞれ説明
上記の文章をベースに少し修正を加えました。

修正内容は以下の通りです。
「省力化コンポーネントは、単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、開発効率の向上が期待できます。一方、多様なデザインが多く求められるような画面では適用効果が低くなるため、慎重な検討や評価が必要となります。」

修正した箇所として
①適応効果が高くなる（低くなる）理由の例を最初に書いてしまうことでイメージを持ってもらう
②バックオフィスシステムやコンシューマ向けシステムなどの例は特徴を述べた後に詳しく説明するためこの文章中では削除

といった修正を加えました。

再度ご確認をお願いいたします。

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、開発効率の向上が期待できます。一方、多様なデザインが多く求められるような画面では適用効果が低くなるため、慎重な検討や評価が必要となります。
`単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、`
入力項目が多くなる画面で適用効果が高く、デザインが単調な場合はより開発効率の向上が期待できる認識です。

いつもデザインに目が行きがちだけど、デザインのところは `AxLayout` を使えるかどうかの違いしかないと思います。

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、開発効率の向上が期待できます。一方、多様なデザインが多く求められるような画面では適用効果が低くなるため、慎重な検討や評価が必要となります。
`多様なデザインが多く求められるような画面では適用効果が低くなる`
多彩なデザインとは何かを説明したほうがいい。

・動的に入力項目が増えるケース
・ボタン以外のイベントが増えるケース

など

見た目の話は `AxLayout` が使えないだけなら、適用効果が低くなるわけではないと思います。

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +- <strong>画面項目が多い</strong>
画面項目＝入力項目だと思うけど認識合っている？

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントが提供する自動レイアウト機能を使うことで、より効率的に項目を配置できます。
```suggestion
  自動レイアウト機能を使うことで、ほぼノンプログラミングで項目を配置できます。
```

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +適用効果の高い画面が多いほど、省略化コンポーネントの効果は高くなります。例として、バックオフィス系のシステムでは、画面項目の多い画面が多数ある、API 呼び出しはボタンのみでも良い、デザインが単調でも許容され自動レイアウト機能を活用できる、などの理由で効果が高い傾向があります。
`例として、バックオフィス系のシステムでは、画面項目の多い画面が多数ある、API 呼び出しはボタンのみでも良い、デザインが単調でも許容され自動レイアウト機能を活用できる、などの理由で効果が高い傾向があります。`

前述した箇条書きを繰り返しているだけな気がします。

「バックオフィス系のシステムは、前述の条件に当てはまる画面が多いため適用効果が高い傾向にあります。」

とかでいいんじゃない？

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、画面項目をカスタムフックで作成しているため、条件分岐による項目数の増減ができません。そのため、動的に変化する入力フォームを実装する場合、省力化コンポーネントでは対応が不十分となります。
対応が不十分とはどういうことでしょうか？

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +  図表や画像などが多い画面では、提供されているコンポーネントがそのまま使用できないため適用効果が低いです。また、取得したデータ値の表示については実装自体は可能ですが、省力化コンポーネントを使用しなくても実装ができるため、導入による効果は低いです。
拡張をしないといけないということなのか、省力化コンポーネントを使っても実装量が削減できないということなのか何を伝えたいのかよくわからなかったです。

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +## 省力化コンポーネントの適用効果が低い画面の特徴
以下の４つをあげていますが、それぞれレベル感が違う気がします。
この順番にした意図はありますか？
- ボタン押下時以外のイベント処理が多い
- 情報やデータを表示するだけの画面が多い
- 画面項目数が動的に変わる
- 画面項目に対してデザインが複数ある場合

**ボタン押下時以外のイベント処理が多い**
省力化コンポーネントを拡張（イベント追加）しないといけない
⇒省力化コストと部品追加コストを比較してメリットがあるなら効果が出る

**情報やデータを表示するだけの画面が多い**
省力化コンポーネントに表示系の部品は無い
⇒使っても使わなくても変わらない。
　※使う場合は部品追加するなどが必要だがそのメリットはない。

**画面項目数が動的に変わる**
省力化コンポーネントを使って実装するとかえって難しい実装になる。
⇒使うことでマイナス

**画面項目に対してデザインが複数ある場合**
省力化コンポーネントを拡張（部品追加）しないといけない
⇒省力化コストと部品追加コストを比較してメリットがあるなら効果が出る

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、画面項目 1 つに対して 1 つのデザインが決まっているため、デザインを変更したい場合には新しいコンポーネントを作成する必要が生じます。そのため、デザインの多様性が求められる画面では、省力化コンポーネントの適用効果が低くなります。
`省力化コンポーネントの適用効果`についての認識を合わせたほうがいいと思います。

省力化コンポーネントのカスタマイズが必要な場合は効果が低いのかな？

2024-08-31 04:39 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +上記の条件に該当するような画面が多くなると、導入の効果が低くなります。例として、デザインの多様が求められるコンシューマー向けのシステムでは適用効果が低い画面が多くなる傾向があります。
`デザインの多様`
⇒ポイントはデザインなのでしょうか？

2024-09-03 01:40 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、画面項目をカスタムフックで作成しているため、条件分岐による項目数の増減ができません。そのため、動的に変化する入力フォームを実装する場合、省力化コンポーネントでは対応が不十分となります。
対応が不十分→実装がかなり複雑になるといった文言に修正しました。

2024-09-03 01:41 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +適用効果の高い画面が多いほど、省略化コンポーネントの効果は高くなります。例として、バックオフィス系のシステムでは、画面項目の多い画面が多数ある、API 呼び出しはボタンのみでも良い、デザインが単調でも許容され自動レイアウト機能を活用できる、などの理由で効果が高い傾向があります。
上記の文言に修正しました。

2024-09-03 01:42 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントが提供する自動レイアウト機能を使うことで、より効率的に項目を配置できます。
提案された文言に修正しました。

2024-09-03 01:46 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、開発効率の向上が期待できます。一方、多様なデザインが多く求められるような画面では適用効果が低くなるため、慎重な検討や評価が必要となります。
`一方、多様なデザインが多く求められるような画面では適用効果が低くなる`を次のように修正しました。

`一方、動的に入力項目が変化するような画面では導入に適さないため、慎重な検討や評価が必要となります`
「多様なデザイン」というのを具体的に「動的に入力項目が変化するような画面」に置き換えました。

2024-09-03 01:46 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、単調なデザインで入力項目が多くなるような画面では適用効果が高くなるため、開発効率の向上が期待できます。一方、多様なデザインが多く求められるような画面では適用効果が低くなるため、慎重な検討や評価が必要となります。
`入力項目が多くなる画面で適用効果が高く、デザインが単調な場合はより開発効率の向上が期待できる認識です。`

上記の文言に修正しました。

2024-09-03 06:49 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-standard.md
> +例として、バックオフィス系のシステムでは、その効果が特に発揮されやすいです。その理由は、画面項目が多く、バリデーションや API の呼び出しが頻繁に行われる場合でも、コード量を抑えつつ高い保守性を維持できるからです。さらに、バックオフィス系システムではこだわったデザインや複雑な画面配置を必要としないため、自動レイアウト機能を活用しやすいという特徴もあります。
長島さんのレビュー指摘も踏まえた結果次のような文言に修正しました。

「適用効果の高い画面が多いほど、省略化コンポーネントの効果は高くなります。バックオフィス系のシステムは、前述の条件に当てはまる画面が多いため適用効果が高い傾向にあります。」

2024-09-03 06:52 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +- <strong>画面項目が多い</strong>
画面項目と入力項目を使い分ける方針で考えます。

入力項目は入力コンポーネント（Itemで定義されるようなコンポーネント）、画面項目は入力項目にボタンなどのコンポーネントを加えたより広義の意味として使用します。

上記を踏まえて再度全体を修正したためご確認をお願いいたします。

2024-09-03 06:57 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +  図表や画像などが多い画面では、提供されているコンポーネントがそのまま使用できないため適用効果が低いです。また、取得したデータ値の表示については実装自体は可能ですが、省力化コンポーネントを使用しなくても実装ができるため、導入による効果は低いです。
`ボタン押下時以外のイベント処理が多い場合`については拡張が必要な画面の特徴に入れました。
`情報やデータを表示するだけの項目が多い`については適用効果が低い画面の特徴に入れました。

2024-09-03 07:20 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +## 省力化コンポーネントの適用効果が低い画面の特徴
順番は特に考えられていなかったため、それぞれを次のように分類しました。

適用が困難な画面
・画面項目数が動的に変わる

適用効果が低い画面
・情報やデータを表示するだけの画面が多い

拡張が必要な画面
・ボタン押下時以外のイベント処理が多い
・画面項目に対してデザインが複数ある場合

以下の構成に合わせて一部内容を修正したため、再度ご確認をお願いいたします。

2024-09-03 07:39 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +上記の条件に該当するような画面が多くなると、導入の効果が低くなります。例として、デザインの多様が求められるコンシューマー向けのシステムでは適用効果が低い画面が多くなる傾向があります。
ポイントはデザインではないです。

`例として、デザインの多様が求められるコンシューマー向けのシステムでは適用効果が低い画面が多くなる傾向があります`について、文言を次のように修正しました。

`コンシューマー向けシステムではこれらの特徴を持つ画面があることもあります。導入検討時の参考にしてください。`

`デザインの多様など`といった文言を使用せず、`これらの特徴を持つ画面が含まれることもある`といった書き方に修正しました。

2024-09-03 07:53 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、画面項目 1 つに対して 1 つのデザインが決まっているため、デザインを変更したい場合には新しいコンポーネントを作成する必要が生じます。そのため、デザインの多様性が求められる画面では、省力化コンポーネントの適用効果が低くなります。
カスタマイズが必要な場合、効果が低くなるとは一概には言えないです。
そのため章の構成としては次のように考えました。

## 省力化コンポーネントの適用効果が低い画面の特徴

### 拡張が必要な画面
- ボタン押下時以外のイベント処理が多い場合
- 画面項目に対してデザインが複数ある場合

どちらの場合も Item やコンポーネントの拡張には導入コストが必要ですが、導入コストよりも適用効果が高いと判断できる場合は拡張ガイドを参考に検討をしてください。

適用効果が低い特徴の中には含んでいますが、`導入コストよりも適用効果が高いと判断できる場合`といった文言を入れ、導入する際に判断していただくように記述をしました。

2024-09-05 04:11 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +   省力化コンポーネントは入力項目に対応した部品を提供しています。しかし、図表や画像など参照項目が多い画面では、それらに対応したコンポーネントが提供されていないため独自の実装が必要になります。独自実装が必要な画面が多いほど適用効果は低くなります。
独自の実装というよりも、省力化コンポーネントを使った場合と使わない場合で実装が変わらないっていうのが正しい表現かなと思いました。
無理やり省力化コンポーネントを使うと、表示項目を ReadOnly の入力項目にして表示するとかになるけど、そんなこと（無駄だから）しないよね？って思う。

2024-09-05 04:11 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +どちらの場合も Item やコンポーネント、イベントの拡張には導入コストが必要ですが、適用効果が高いと判断できる場合は[拡張ガイド](../category/拡張ガイド/)を参考に検討をしてください。
導入コストが必要とはどういうことだろう？
拡張が必要で、適用画面数（省力化できるコスト）と拡張コストを天秤にかけたときに省力化コストが優位なら拡張してねってことが言いたいんだよね？

2024-09-05 04:11 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、入力項目をカスタムフックで作成しているため、条件分岐による項目数の増減ができません。そのため、動的に変化する入力フォームを実装する場合、省力化コンポーネントでは実装が困難または複雑になり得るため適用をお勧めしません。
例えばこういった画面という例を出せないかな

2024-09-05 04:11 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +本章では、導入指標として省力化コンポーネントの適用効果が高い画面および省力化コンポーネントの適用効果が低い画面の特徴についてそれぞれ説明をします。
「適用効果」が何を指しているかが分かった方が良いですね。

2024-09-05 04:11 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、入力項目が多くなる画面で適用効果が高く、デザインが単調な場合はより開発効率の向上が期待できます。一方、動的に入力項目が変化するような画面では導入に適さないため、慎重な検討や評価が必要となります。
「入力項目が多くなる画面で適用効果が高く」ってところの理由が知りたくなります。

2024-09-05 05:33 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +省力化コンポーネントは、入力項目が多くなる画面で適用効果が高く、デザインが単調な場合はより開発効率の向上が期待できます。一方、動的に入力項目が変化するような画面では導入に適さないため、慎重な検討や評価が必要となります。
「入力項目が多くなる画面で適用効果が高く」の理由については特徴の1つ目に述べる予定です。入力項目ではなく画面項目に修正しました。

2024-09-05 05:35 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +本章では、導入指標として省力化コンポーネントの適用効果が高い画面および省力化コンポーネントの適用効果が低い画面の特徴についてそれぞれ説明をします。
適用効果が高い：コンポーネントが再利用できコード量を削減できる
適用効果が低い：コンポーネントの再利用ができない場合や実装が困難
上記のように定義して導入の文章に付け足しました。

2024-09-05 05:36 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +  省力化コンポーネントでは、入力項目をカスタムフックで作成しているため、条件分岐による項目数の増減ができません。そのため、動的に変化する入力フォームを実装する場合、省力化コンポーネントでは実装が困難または複雑になり得るため適用をお勧めしません。
登録フォームの例を出して説明する文章を付け足しました。

2024-09-05 05:38 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +どちらの場合も Item やコンポーネント、イベントの拡張には導入コストが必要ですが、適用効果が高いと判断できる場合は[拡張ガイド](../category/拡張ガイド/)を参考に検討をしてください。
おっしゃる通りです。
「どちらの場合もコンポーネントやイベントを拡張するためのコストが必要ですが、適用画面数が多く導入効果が高いと判断できる場合」といった文言に修正しました。
拡張が必要な画面ではItemの例がなかったため、Itemについては触れないようにしました。

2024-09-05 05:39 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +   省力化コンポーネントは入力項目に対応した部品を提供しています。しかし、図表や画像など参照項目が多い画面では、それらに対応したコンポーネントが提供されていないため独自の実装が必要になります。独自実装が必要な画面が多いほど適用効果は低くなります。
次のように文章を修正しました。
「省力化コンポーネントは入力項目に対応した部品を提供しています。しかし、図表や画像など参照項目が多い画面では、それらに対応したコンポーネントが提供されていません。そのため省力化コンポーネントを使用しなくても実装方法は変わらないため適用効果は低いです。」

2024-09-06 01:20 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +   省力化コンポーネントは入力項目に対応した部品を提供しています。しかし、図表や画像など参照項目が多い画面では、それらに対応したコンポーネントが提供されていないため独自の実装が必要になります。独自実装が必要な画面が多いほど適用効果は低くなります。
「省力化コンポーネントは、入力フィールドやイベントハンドリングの実装時にコードの重複を減らす目的で開発されました。しかし、図表や画像などの参照要素が多く含まれる画面においては、これらのコンポーネントによるコード削減の効果は限定的ですので、必ずしも使用する必要はありません。」

これくらいの感じでいいと思います。
特に、従来の方法で簡潔かについては触れる必要はないと思う。

2024-09-06 01:41 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +本章では、導入指標として省力化コンポーネントの適用効果が高い画面および省力化コンポーネントの適用効果が低い画面の特徴についてそれぞれ説明をします。
「適用効果が高いとは、コンポーネントが再利用できコード量を削減できることを指します。逆に適用効果が低いとは、コンポーネントの再利用ができない場合や実装が困難な場合を指します。」
この文章からあまり得られるものが無いと思います。

「はじめに」で以下のように省力化コンポーネントについて紹介しています。
「上記のような特徴を持つ省力化コンポーネントを用いた場合、従来手法の 約 30% ～ 40%のコード量で同様の画面を実装することができます。省力化コンポーネントを使用することで、冗長なコードを排除し、開発生産性を向上させることが可能となります。また、共通のコンポーネントを使用しているため、メンテナンス性の高いコードベースを維持することも可能となります。」

結局のところ、ここで書いているメリットを享受しやすい画面がどういった画面なのかの紹介なので、初めにの特徴やコンセプトのところをどこまで頭に入れて文章が書けているかって感じなのかなと思いました。

文章だけを書き換えても収集つかない気がするので、まずは以下を整理するべきだと思いました。
・対象読者（誰に向けて書いているのか）
・この章の目的
・この章を読み終えたときに読者はどうなっていて欲しいか

上記を整理したうえで、自分でも読み直してみて目的は達成できそうかを見直してみてほしいです。

2024-09-06 01:42 UTC, nagashi84 commented on docs/know-cs-component/introduction-index.md
> +コンシューマー向けシステムではこれらの特徴を持つ画面が含まれることもあります。導入検討時の参考にしてください。
この文章ってどこにかかっているのかな？

2024-09-09 08:01 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +   省力化コンポーネントは入力項目に対応した部品を提供しています。しかし、図表や画像など参照項目が多い画面では、それらに対応したコンポーネントが提供されていないため独自の実装が必要になります。独自実装が必要な画面が多いほど適用効果は低くなります。
上記の文章をベースに少し修正しました。
「省力化コンポーネントは、入力フィールドやイベントハンドリングの実装時にコードの重複を減らす目的で開発されました。そのため、図表や画像、読み取り項目といった参照系の要素が多く含まれる画面においては、省力化コンポーネントによるコード削減の効果は限定的になります。」

2024-09-09 08:21 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +コンシューマー向けシステムではこれらの特徴を持つ画面が含まれることもあります。導入検討時の参考にしてください。
「コンシューマー向けのシステムでは～」については導入効果が得られにくい画面の特徴のすべてにかかっています。
infoを用いて「前述の4つの条件を持つ画面が～」のようにすべての特徴を含むような文章に修正しました。

2024-09-09 08:32 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +本章では、導入指標として省力化コンポーネントの適用効果が高い画面および省力化コンポーネントの適用効果が低い画面の特徴についてそれぞれ説明をします。
以下の3点について整理しました。
・対象読者（誰に向けて書いているのか）
　・作る画面は決まっていて、それを実装する際に省力化コンポーネントを利用するべきかを迷っている人
 
・この章の目的
　・導入効果が高い画面と導入効果が得られにくい画面の特徴を説明することで、読者に省力化コンポーネントを導入するかどうかの判断材料を提供すること
 
・この章を読み終えたときに読者はどうなっていて欲しいか
　・自分たちが作る画面を実装する際に省力化コンポーネントを使うかの判断がつく
　
　
　適用効果の高い画面はセクションの「特徴」に準拠しており、特徴はセクションの「はじめに」に準拠しているため、「はじめに」に書かれている省力化コンポーネントのメリットを享受できるような文章になっています。

また、修正前は特徴をただ羅列した状態→最初に特徴を8つ羅列し、どのような画面に当てはまるか読者に考えてもらう。その上で、それぞれの内容について読んでもらう。
といった対象読者に沿った構成に修正しました。



　

2024-09-10 00:12 UTC, tashxii requested changes

2024-09-10 00:12 UTC, tashxii commented on docs/know-cs-component/introduction-index.md
> +<hr />
水平線があっても、項目の意味が箇条書きの途中で変わるようにすべきではありません。
（箇条書きは、同等のものを並べるときに使うものです）

上半分と下半分で相反する項目が8個ならんでいるので、上半分に「効果の出やすい特徴」、下半分に「効果の出にくい特徴」のようなラベルを貼るべきです。

2024-09-10 00:12 UTC, tashxii commented on docs/know-cs-component/introduction-index.md
> +ただし、パラメータとしてスタイル定義を渡すことで、1 つのコンポーネントでも多少のデザインのカスタマイズは可能です。
「スタイル定義」というより、「CSSのクラス名」を渡すと書いたほうがわかりやすいでしょう。

2024-09-10 00:25 UTC, nagashi84 approved these changes

2024-09-10 01:30 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +ただし、パラメータとしてスタイル定義を渡すことで、1 つのコンポーネントでも多少のデザインのカスタマイズは可能です。
「CSSのクラス名」といった文言に修正しました。

2024-09-10 04:03 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +<hr />
上の4項目を「カテゴリー1」、下の4項目を「カテゴリー２」といったラベル名にしました。
その理由として、最初から「効果の出やすい特徴」、「効果の出にくい特徴」を伝えずに画面の特徴だけを考えてもらうことで先入観を持たせずに判断して欲しいといった意図があるためです。

2024-09-11 00:08 UTC, tashxii requested changes

2024-09-11 00:08 UTC, tashxii commented on docs/know-cs-component/introduction-index.md
> +<h4><u>★ カテゴリー１ </u></h4>
「カテゴリー」１と２と書くと違和感を感じました。何かしらの単語を使った文言で書いてほしいです。
「省力化コンポーネントに適した画面の特徴」、「省力化コンポーネントに適さない画面の特徴」
「効果の高い画面の特徴」、「効果の出にくい画面の特徴」
でも何でも良いので、「カテゴリー」はやめてください

2024-09-11 00:25 UTC, RenTakemoto-10157 commented on docs/know-cs-component/introduction-index.md
> +<h4><u>★ カテゴリー１ </u></h4>
「カテゴリー１」を「効果の高い画面の特徴」、「カテゴリー２」を「効果の出にくい画面の特徴」といった文言に修正しました。

2024-09-11 01:54 UTC, tashxii approved these changes

2024-09-11 04:04 UTC, merged