「省力化コンポーネントを知る > コンセプト」の内容作成
Fintan-contents/dev-react-cs-document pull request #11
Opened 2024-08-30 00:32 UTC by MinkToo331

レビューよろしくお願いいたします。

レビュー準備が完了しているもの
- 全体構成
- 文章の内容
- ソースコード

残作業
- 特になし

2024-08-30 01:48 UTC, tashxii requested changes

2024-08-30 01:48 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +[入力項目に必要なパラメータの集約](#入力項目に必要なパラメータの集約)で述べたように、Item は 1 つの入力項目に関連する定義を集約して保持しています。そして、View は画面内の Item を集約して保持しています。言い換えると、View は 1 つの画面に関連する定義を集約して保持していることになります。1 つの画面に関連する定義を集約することで、以下に示す 3 つの操作が可能となり
AIに校正させました。理由は、`「1つの画面」が何度もでてきて冗長に感じます。` です。

下
次の文章を校正してください。「1つの画面」が何度もでてきて冗長に感じます。
「入力項目に必要なパラメータの集約で述べたように、Item は 1 つの入力項目に関連する定義を集約して保持しています。そして、View は画面内の Item を集約して保持しています。言い換えると、View は 1 つの画面に関連する定義を集約して保持していることになります。1 つの画面に関連する定義を集約することで、以下に示す 3 つの操作が可能となります。」

AI Chat Bot
以下のように文章を校正しました。冗長さを避けるために「1つの画面」に関する表現を調整しました。

「入力項目に必要なパラメータの集約で述べたように、Item は1つの入力項目に関連する定義を集約して保持しています。そして、View は画面内の Item を集約して保持しています。言い換えると、View は画面に関連する定義を集約して保持していることになります。これにより、以下に示す3つの操作が可能となります。」

ご確認ください。

2024-08-30 01:48 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +}
L119-L140までの内部実装は出さなくてよいです。（`開発側`視点のコードに、`利用者側`は興味ないです）

「画面項目のパラメータは、Itemに集約されているため、AxInputText コンポーネント（テキスト入力のコンポーネント）には次のように、Itemを渡すだけで実装できます。
ラベルの配置やバリデーション結果のメッセージ、`input`の`onChange`のハンドラは、渡されたItemの情報からコンポーネントの内部で実装されます。利用者は、パラメータを渡すだけでよいのです。」

例としては、`利用者側`視点でのコード例と、画面例（ラベルやバリデーションメッセージが表示された入力コンポ）が書かれているべきです。

特に、ボタンもそうですが、画面例がないので、わかりにくいです。

2024-08-30 01:48 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +};
ここも内部実装なので読者にとって関係ないところです。
ボタンのオプション指定の例と、そのオプションでボタンがどう動くかの画面例を載せてください。

2024-08-30 01:48 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +  API 呼び出し処理とバリデーション実行処理を定義したコールバック関数、ローディング中のスピナー表示機能、ボタン押下後のメッセージ表示機能をボタンコンポーネントの内部に組み込みます。
「API 呼び出し処理・・・表示機能、ボタン押下時の確認ダイアログの表示等は、ボタンコンポーネントの中に組み込まれており、利用者は、eventと振る舞いをパラメータとしてボタンに渡すだけで動作するようになっています。」

そして、コード例と画面例（Spinnerが回って成功メッセージがでるようなGifでよい）を載せてください。

2024-08-31 04:53 UTC, nagashi84 commented on docs/know-cs-component/basic-concepts.md
> +}
私も以下があるとよいと思いました。
・利用者視点のコード例
・そのコードで表示される画面例
　（Gif がいいか、パターン毎の画像がいいかは悩みますが）

2024-09-02 00:40 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +[入力項目に必要なパラメータの集約](#入力項目に必要なパラメータの集約)で述べたように、Item は 1 つの入力項目に関連する定義を集約して保持しています。そして、View は画面内の Item を集約して保持しています。言い換えると、View は 1 つの画面に関連する定義を集約して保持していることになります。1 つの画面に関連する定義を集約することで、以下に示す 3 つの操作が可能となり
AIチャットの回答を取り入れました。（同様の内容で、「1つの画面」の冗長さが解消されていたためです。）
プロンプトの書き方含め、FBいただきありがとうございます。

2024-09-03 01:46 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +}
利用者視点のコード例、およびそのコードで表示される画面例を載せました。
内部実装は参考情報として開閉式のinformation欄に乗せることにしました。

2024-09-03 01:47 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +};
利用者視点のコード例、およびそのコードで表示されるボタンの動作例(GIF)を載せました。
内部実装は参考情報として開閉式のinformation欄に乗せることにしました。

2024-09-03 01:48 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +  API 呼び出し処理とバリデーション実行処理を定義したコールバック関数、ローディング中のスピナー表示機能、ボタン押下後のメッセージ表示機能をボタンコンポーネントの内部に組み込みます。
「API 呼び出し処理とバリデーション実行処理を定義したコールバック関数、ローディング中のスピナー表示機能、ボタン押下後のメッセージ表示機能をボタンコンポーネントの内部に組み込みます。それによって、実装者はイベントと振る舞いをパラメータとしてコンポーネントに渡すだけで必要な機能を実現することができます。」
とし、そのあとにGIFとコード例を載せるようにしました。
また、eventが突然出てきてしまうので、informationにイベントの説明を追加しました。

2024-09-03 04:51 UTC, tashxii requested changes

2024-09-03 04:51 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +ボタンコンポーネントのパラメータとして登場している`event`とは、ユーザーの操作(ボタンクリックなど)に応じて実行される処理を定義したものです。主なイベント処理としては API リクエストがあります。
「APIリクエスト」より「API呼び出し」のほうが良いと思います

2024-09-03 06:55 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +ボタンコンポーネントのパラメータとして登場している`event`とは、ユーザーの操作(ボタンクリックなど)に応じて実行される処理を定義したものです。主なイベント処理としては API リクエストがあります。
「APIリクエスト」を「API呼び出し」に変更しました。
（他の箇所でも「API呼び出し」という単語が使われていたので、統一性という観点で見てもこちらの方が良いと判断しました。）

2024-09-03 06:57 UTC, tashxii approved these changes

2024-09-03 07:02 UTC, merged