「導入ガイド > 導入ツール」の作成
Fintan-contents/dev-react-cs-document pull request #16
Opened 2024-09-18 09:30 UTC by RenTakemoto-10157

2024-09-20 04:26 UTC, tashxii requested changes

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +本節では、導入ツールを実行して省力化コンポーネントに必要な資材をインストールする手順について解説します。
「解説」は内容と合わないので、「説明」にしてください。

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +エクスプローラーで該当のフォルダを開き、ターミナル上にドラッグ＆ドロップをすることでパスが自動で入力されます。この操作により、パスを手入力する手間と打ち間違いのリスクを減らすことが可能となります。
「リスク」も大げさな表現です。

>「この操作により、パスを手入力する手間と打ち間違いのリスクを減らすことが可能となります。」

「これにより、手入力する手間や打ち間違いを減らすことができます。」
位で良いとおもいます。

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +Orval は OpenAPI 仕様からソースコードを自動生成することができます。一方で TanStack Query ではソースコードを手動で生成します。ソースコードを自動生成することで開発効率が上がるため、本ドキュメントでは Orval を推奨しています。
自動生成と手動の表現が細かいところで正しくありませんし、冗長です。
また、本ドキュメントが推奨するわけではないです。本ツールとするか、省略するべきです。

>「Orval は OpenAPI 仕様からソースコードを自動生成することができます。一方で TanStack Query ではソースコードを手動で生成します。」

修正例です。
「Orval は OpenAPI 仕様からソースコードを自動生成するツールで、「Orval」の選択肢を選ぶと省力化コンポーネントはこの自動生成されたコードに対応する部品をインストールします。自動生成しないでTanStack Queryを直接使う場合は、「TanStack Query」を選んでください。自動生成の方が開発効率が上がるため、 Orval を推奨しています。」

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +デモ画面は省力化コンポーネントを使用して作成されているため、デモ画面を含めることで実装方法や動作イメージなどを確認することができます。
細かい表現に違和感があり、冗長な箇所があります。

> デモ画面は省力化コンポーネントを使用して作成されているため、デモ画面を含めることで・・・

「デモ画面自身も省力化コンポーネントを使用して作成されているため、実装方法や動作イメージなどを確認することができます。」

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +  ↓ C:\your\projects\
projectsというのは複数形なのでおかしいです。この例にするなら、projectにしてください。

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +`src` ディレクトリがある場合は、その配下にコピー先を指定するようにしてください。`src` 配下に指定されなかった場合、デモ画面ファイル内の import 文が適切に設定されない可能性があります。
ここも、状態を述べているだけで、何をしたらよいかが抜けています。

> `src` 配下に指定されなかった場合、デモ画面ファイル内の import 文が適切に設定されない可能性があります。

「`src` 配下に指定されなかった場合、デモ画面ファイル内の import 文が適切に設定されない場合があります。その場合は、import 文を編集して直す必要があります。」

2024-09-20 04:26 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +次節で紹介する<strong>インストール資材</strong>では、コピーされるディレクトリの構成やインストールされるライブラリについて紹介します。
「紹介するｘｘｘで、ｘｘｘについて紹介します」という文章になっています。
「紹介するｘｘｘで、ｘｘｘについて説明します」に直してください。

2024-09-20 09:36 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +本節では、導入ツールを実行して省力化コンポーネントに必要な資材をインストールする手順について解説します。
「説明」に修正しました。

2024-09-20 09:38 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +エクスプローラーで該当のフォルダを開き、ターミナル上にドラッグ＆ドロップをすることでパスが自動で入力されます。この操作により、パスを手入力する手間と打ち間違いのリスクを減らすことが可能となります。
>これにより、手入力する手間や打ち間違いを減らすことができます。
上記の文章に修正しました。

2024-09-20 09:39 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +Orval は OpenAPI 仕様からソースコードを自動生成することができます。一方で TanStack Query ではソースコードを手動で生成します。ソースコードを自動生成することで開発効率が上がるため、本ドキュメントでは Orval を推奨しています。
「Orval は OpenAPI 仕様からソースコードを自動生成するツールです。「Orval」を選択すると、導入ツールは自動生成されるコードに対応する部品をインストールします。自動生成を行わずに TanStack Query を直接使用する場合は、「TanStack Query」を選んでください。自動生成の方が開発効率が上がるため、 Orval を推奨しています。」

2024-09-20 09:42 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +デモ画面は省力化コンポーネントを使用して作成されているため、デモ画面を含めることで実装方法や動作イメージなどを確認することができます。
> デモ画面自身も省力化コンポーネントを使用して作成されているため、実装方法や動作イメージなどを確認することができます。
上記の文章に修正しました。

2024-09-20 09:44 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +  ↓ C:\your\projects\
「project」といった単数形に修正しました。

2024-09-20 09:44 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +`src` ディレクトリがある場合は、その配下にコピー先を指定するようにしてください。`src` 配下に指定されなかった場合、デモ画面ファイル内の import 文が適切に設定されない可能性があります。
> `src` 配下に指定されなかった場合、デモ画面ファイル内の import 文が適切に設定されない場合があります。その場合は、import 文を編集して直す必要があります。

上記の文章に修正しました。

2024-09-20 09:45 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +次節で紹介する<strong>インストール資材</strong>では、コピーされるディレクトリの構成やインストールされるライブラリについて紹介します。
「紹介するｘｘｘで、ｘｘｘについて説明します」の形に修正しました。

2024-09-26 05:36 UTC, tashxii requested changes

2024-09-26 05:36 UTC, tashxii commented on docs/introduction-guide/introduction-tool.md
> +Orval は OpenAPI 仕様からソースコードを自動生成するツールです。「Orval」を選択すると、導入ツールは自動生成されるコードに対応する部品をインストールします。自動生成を行わずに TanStack Query を直接使用する場合は、「TanStack Query」を選択肢してください。自動生成の方が開発効率が上がるため、 Orval を推奨しています。
Typo：「TanStack Query」を選択肢してください。
→ 「TanStack Query」を選択してください。

2024-09-26 05:42 UTC, nagashi84 approved these changes

2024-09-26 05:45 UTC, RenTakemoto-10157 commented on docs/introduction-guide/introduction-tool.md
> +Orval は OpenAPI 仕様からソースコードを自動生成するツールです。「Orval」を選択すると、導入ツールは自動生成されるコードに対応する部品をインストールします。自動生成を行わずに TanStack Query を直接使用する場合は、「TanStack Query」を選択肢してください。自動生成の方が開発効率が上がるため、 Orval を推奨しています。
> 「TanStack Query」を選択してください

タイピングミスをしていたため、上記の文章に修正しました。

2024-10-02 01:27 UTC, tashxii approved these changes

2024-10-02 01:27 UTC, merged