「導入ガイド > 導入後の作業」の作成
Fintan-contents/dev-react-cs-document pull request #17
Opened 2024-09-19 06:13 UTC by RenTakemoto-10157

残タスク
・Storybookのドキュメント内容記載
・サンプルアプリのリンク先修正

2024-09-20 04:40 UTC, tashxii requested changes

2024-09-20 04:40 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +本項の対象読者は、デモ画面を含めるかの選択で「はい」を選択した方です。
「本項」だとページと言う意味に捉えられ、全体をスキップされるかもしれません。
「本節」か、「本セクション」のほうがより適切な単語になります。

また、２行で本項、本項と２回出ており冗長に感じます。
「デモ画面を含めるかの選択で「いいえ」を選択した方はこの作業は実施する必要がありません。」
と、ここでは１行で書けばわかることです。

2024-09-20 04:40 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +「TanStack Query」を選択した方は本項の作業を実施する必要がありません。
> 本項の対象読者は、API 生成方式の選択で「Orval」を選択した方です。  
>「TanStack Query」を選択した方は本項の作業を実施する必要がありません。

「API 生成方式の選択で「TanStack Query」を選択した方はこの作業は実施する必要がありません。」
でよいかと。

2024-09-20 04:40 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +OpenAPI 仕様が未作成の場合は上記のサンプルを使用してください。
サンプルなのでプロジェクトで使用する意味がないです。何を想定してサンプルを使うのですか？

2024-09-20 04:40 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +OpenAPI 仕様が定義された `oepnapi.yml` をルート配下に配置します。
文章では、ルート配下となっているのに、openapi/openapi.ymlとなっているのはどうしてですか？
「配下」という単語はどういう意味で使っていますか？
「※配置場所はあくまで一例です」というのがあればよいだけではないでしょうか。

2024-09-20 04:40 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +`orval.config.ts` という Orval の設定ファイルをルート配下に作成します。
ここでの「配下」と上の「配下」の意味は同じですか？
ここは、「直下」が厳密な意味で正しいのではないでしょうか。

2024-09-24 00:10 UTC, RenTakemoto-10157 commented on docs/introduction-guide/working-after-introduction.md
> +「TanStack Query」を選択した方は本項の作業を実施する必要がありません。
「API 生成方式の選択で「TanStack Query」を選択した方は、この作業を実施する必要がありません。」
上記の文章に修正しました。

2024-09-24 08:08 UTC, RenTakemoto-10157 commented on docs/introduction-guide/working-after-introduction.md
> +本項の対象読者は、デモ画面を含めるかの選択で「はい」を選択した方です。
本ドキュメントでは「章、節、項」の順番で統一する予定です。
「章、節、項」
https://www.yorimichi-life.com/headline-part-chapter-section/

具体的には「はじめに」や「省力化コンポーネントを知る」などは「章」、省力化コンポーネントを知るの書くセクションは「節」、各節の小見出しを「項」で考えています。

> ２行で本項、本項と２回出ており冗長に感じます。

本項といった文言は不要のため削除しました。

> デモ画面を含めるかの選択で「いいえ」を選択した方はこの作業は実施する必要がありません

上記の文言に修正しました。

2024-09-24 08:09 UTC, RenTakemoto-10157 commented on docs/introduction-guide/working-after-introduction.md
> +OpenAPI 仕様が未作成の場合は上記のサンプルを使用してください。
> 仕様が未作成の場合は上記のサンプルを使用してください。

使用する必要がないため上記の文言を削除しました。

2024-09-24 08:10 UTC, RenTakemoto-10157 commented on docs/introduction-guide/working-after-introduction.md
> +`orval.config.ts` という Orval の設定ファイルをルート配下に作成します。
「直下」に修正しました。

2024-09-24 08:16 UTC, RenTakemoto-10157 commented on docs/introduction-guide/working-after-introduction.md
> +OpenAPI 仕様が定義された `oepnapi.yml` をルート配下に配置します。
配下：指定したディレクトリの下の階層すべてに該当
直下：指定したディレクトリの直接的な階層のみ該当
のように使い分けています。

ルート配下といった文言を削除し、ディレクトリの図の中に「配置場所はあくまで一例です」といった文言を追加しました。

2024-09-26 13:55 UTC, nagashi84 approved these changes

2024-10-02 01:29 UTC, tashxii approved these changes

2024-10-02 01:29 UTC, merged