「はじめに～導入ガイド」の全体修正
Fintan-contents/dev-react-cs-document pull request #19
Opened 2024-10-07 04:42 UTC by RenTakemoto-10157

修正箇所

2024-10-15 07:34 UTC, nagashi84 commented on docs/introduction-guide/installed-materials.md
> +本節では、導入ツールによってプロジェクトにインストールされる資材について説明をします。
修正前の方が簡潔でいいかな

2024-10-15 07:34 UTC, nagashi84 commented on docs/introduction-guide/prior-preparation.md
> +本章では、省力化コンポーネントをプロジェクトに導入するための手順について説明をします。
「説明をします」は冗長な気がするので、「説明します」でいいと思う。

2024-10-15 07:34 UTC, nagashi84 commented on docs/introduction-guide/prior-preparation.md
> +まず初めに、事前準備として必要となる以下の 3 つの作業について説明をします。
「説明をします」は冗長な気がするので、「説明します」でいいと思う。

2024-10-15 07:34 UTC, nagashi84 commented on docs/know-cs-component/basic-concepts.md
> +本コンセプトを適用することで、「画面全体のバリデーションスキーマの定義」による冗長さを解消することができます。
「解消できます」でいいかと

2024-10-15 07:34 UTC, nagashi84 commented on docs/know-cs-component/basic-concepts.md
> +本コンセプトを適用することで、「画面全体のバリデーションスキーマの定義」による冗長さを解消することができます。
他にも似たようなのがありました。

2024-10-15 07:34 UTC, nagashi84 commented on docs/know-cs-component/features.md
> +また、文字列型以外にも、数値型のバリデーションを定義する `numberRule` や、配列型のバリデーションを定義する `stringArrayRule` を使用することができます。
「使用できます」でいいかと

2024-10-17 01:17 UTC, tashxii requested changes

2024-10-17 01:17 UTC, tashxii commented on docs/introduction-guide/working-after-introduction.md
> +`orval.config.ts` という Orval の設定ファイルをルート直下に作成します。
「ルート直下」ではなく下の例と併せて「プロジェクトのルート直下」としたほうがよいです。

2024-10-17 01:17 UTC, tashxii commented on docs/know-cs-component/basic-concepts.md
> +なお、各入力部品コンポーネントに渡すことのできる Item クラスは、その入力部品の種類に対応する Item クラスのみになっており、型チェックの対象となります。(例： `AxInputText` コンポーネントには、 `CsInputTextItem` クラスの Item のみ渡すことが可能です。)
「型チェックの対象となります」だからどうした？と感じるので、
「型チェックの対象となり、Itemを誤った入力部品コンポーネントに渡すというミスを減らせます。」
と理由も書くべきです。

2024-10-17 09:26 UTC, MinkToo331 commented on docs/introduction-guide/installed-materials.md
> +本節では、導入ツールによってプロジェクトにインストールされる資材について説明をします。
「～説明します。」に修正しました。
[冗長な表現を排除](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/4dd3a3bcea0e5e16336b6fb5ab43ecaf0610115c)

2024-10-17 09:27 UTC, MinkToo331 commented on docs/introduction-guide/prior-preparation.md
> +本章では、省力化コンポーネントをプロジェクトに導入するための手順について説明をします。
「～説明します。」に修正しました。

コミット：[冗長な表現を排除](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/4dd3a3bcea0e5e16336b6fb5ab43ecaf0610115c)

2024-10-17 09:27 UTC, MinkToo331 commented on docs/introduction-guide/prior-preparation.md
> +まず初めに、事前準備として必要となる以下の 3 つの作業について説明をします。
「説明します」に修正しました。

コミット：[冗長な表現を排除](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/4dd3a3bcea0e5e16336b6fb5ab43ecaf0610115c)

2024-10-17 09:27 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +本コンセプトを適用することで、「画面全体のバリデーションスキーマの定義」による冗長さを解消することができます。
該当する箇所全てを「解消できます」に修正しました。

コミット：[冗長な表現を排除](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/4dd3a3bcea0e5e16336b6fb5ab43ecaf0610115c)

2024-10-17 09:28 UTC, MinkToo331 commented on docs/know-cs-component/features.md
> +また、文字列型以外にも、数値型のバリデーションを定義する `numberRule` や、配列型のバリデーションを定義する `stringArrayRule` を使用することができます。
「使用できます」に修正しました。

コミット：[冗長な表現を排除](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/4dd3a3bcea0e5e16336b6fb5ab43ecaf0610115c)

2024-10-17 09:29 UTC, MinkToo331 commented on docs/introduction-guide/working-after-introduction.md
> +`orval.config.ts` という Orval の設定ファイルをルート直下に作成します。
「プロジェクトのルート直下」に修正しました。

コミット：[その他項目の指摘対応](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/1f690a39fb795499151c0c2e1a15b389ea376e6b)

2024-10-17 09:30 UTC, MinkToo331 commented on docs/know-cs-component/basic-concepts.md
> +なお、各入力部品コンポーネントに渡すことのできる Item クラスは、その入力部品の種類に対応する Item クラスのみになっており、型チェックの対象となります。(例： `AxInputText` コンポーネントには、 `CsInputTextItem` クラスの Item のみ渡すことが可能です。)
> なお、型チェックにより、各入力部品コンポーネントに渡せる Item クラスは、その入力部品の種類に対応する Item クラスに制限されます。これにより、Item を誤った入力部品コンポーネントに渡すというミスを減らせます。(例： `AxInputText` コンポーネントには、 `CsInputTextItem` クラスの Item のみ渡すことが可能です。)  
に修正しました。

[その他項目の指摘対応](https://github.com/Fintan-contents/dev-react-cs-document/pull/19/commits/1f690a39fb795499151c0c2e1a15b389ea376e6b)

2024-10-17 23:51 UTC, tashxii approved these changes

2024-10-21 23:32 UTC, nagashi84 approved these changes

2024-10-21 23:32 UTC, merged