実装ガイド > 画面を作る > 「画面を定義する」「バリデーションを定義する」「入力項目を配置する」の作成
Fintan-contents/dev-react-cs-document pull request #20
Opened 2024-10-11 06:20 UTC by MinkToo331

2024-10-15 04:38 UTC, tashxii requested changes

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-validation.md
> +`useCsView` の第二引数に `validationTrigger: "onBlur"` を指定することで、各入力フォームのフォーカスが外れたタイミングでバリデーションを実施することができるようになります。
「実施できます。」でよいと思います。
（「～することができるようになります。」は冗長な表現で、「～できます」と言い換えれます。TextLintなどの導入も検討してください）

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/goal.md
> +また、入力項目に対してバリデーションルールを定義し、バリデーションを実施することができるようになります。
ここも冗長です。「実施できます。」でよいと思います。

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/goal.md
> +本節を通して、以下に示すような入力項目が複数並んだ画面を作ることができます。
「作ることができます。」→「作れます。」

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-validation.md
> +省力化コンポーネントが提供するボタン部品を使用することで、ボタン押下時にバリデーションを実施することができます。
「実施することができます。」→「実施できます。」

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-validation.md
> +    (label: string, _: string) => "半角数字で入力してください。"
２番目のstringが「_」になっている理由がわかりません。labelとnewValueなので両方省略するか、書くかのどちらかで、片方だけ省略になるのは変です。両方書くほうが例としてはわかりやすいとおもいます。

2024-10-15 04:38 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-screen.md
> +## View の初期化を定義する
「Viewの初期化を定義」という言葉に違和感を感じます。初期化が動詞としても使えるため。
「Viewを初期化する」で良いのではないでしょうか。

2024-10-23 01:18 UTC, nagashi84 commented on docs/implementation-guide/create-register-screen/define-screen.md
> +View を初期化するためには、 `useCsView` という省力化コンポーネントのフックを使用します。 `useCsView` の引数には、`useCsXxxItem*` というフックを使って必要なパラメータを設定した Item を渡します。（※ `useCsXxxItem` の `Xxx` は Item の種類に応じて異なります。）
> `useCsXxxItem*` というフックを使って必要なパラメータを設定した

Item のところで「初期化」を使わなかったことに意図はありますか？
後述の INFO の中では「初期化」を使っています。

> Item の初期化に使用する `useCsXxxItem`

Item も初期化が必要でViewには初期化したItemを渡すという方が自然かなと思いました。

2024-10-23 01:18 UTC, nagashi84 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +      stringRule(true, 3, 30)
対象の箇所にコードハイライト入れたいです。

https://griponminds.jp/blog/docusaurus-04/#%E8%A1%8C%E3%83%8F%E3%82%A4%E3%83%A9%E3%82%A4%E3%83%88

2024-10-23 01:18 UTC, nagashi84 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +    customValidationRules: buildInCustomValidationRules,
ここにもハイライトを入れたい

2024-10-25 05:14 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +`useCsView` の第二引数に `validationTrigger: "onBlur"` を指定することで、各入力フォームのフォーカスが外れたタイミングでバリデーションを実施することができるようになります。
「実施できます。」に変えました。
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/2ad6bbf682d9be0ca09c81d3d0a130f7193bb7c0

2024-10-25 05:14 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/goal.md
> +また、入力項目に対してバリデーションルールを定義し、バリデーションを実施することができるようになります。
「実施できます。」に変えました。
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/2ad6bbf682d9be0ca09c81d3d0a130f7193bb7c0

2024-10-25 05:17 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/goal.md
> +本節を通して、以下に示すような入力項目が複数並んだ画面を作ることができます。
> 本節を通して、次の 2 つの実装方法を理解できます。
> ・複数の入力項目が並んだ画面を作成する
> ・ボタン押下時やフォーカスアウト時にバリデーションを実施する

文章構成を変更したため、ご指摘の箇所は無くなりました。ただし、変更後の文章に冗長な表現がないように注意をしています。
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/2ad6bbf682d9be0ca09c81d3d0a130f7193bb7c0

2024-10-25 05:17 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +省力化コンポーネントが提供するボタン部品を使用することで、ボタン押下時にバリデーションを実施することができます。
「実施できます。」に変えています。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/2ad6bbf682d9be0ca09c81d3d0a130f7193bb7c0

2024-10-25 05:20 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +    (label: string, _: string) => "半角数字で入力してください。"
導入リポジトリの最新化作業の中で`buildInCustomValidationRules`も修正したため、そちらの内容に更新しています。
メッセージの引数でとれる変数の種類(label, name, value)については、「拡張ガイド>カスタムバリデーションルールを作る」で触れる予定です。この説ではlabelだけを使用します。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/b510f27b8c2ea40f395e5394fb784bfd59d0f902

2024-10-25 05:21 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-screen.md
> +## View の初期化を定義する
「Viewを初期化する」に修正しました。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/575247f3ba9ffa35a719b4f9717b6c038686febc

2024-10-25 05:22 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-screen.md
> +View を初期化するためには、 `useCsView` という省力化コンポーネントのフックを使用します。 `useCsView` の引数には、`useCsXxxItem*` というフックを使って必要なパラメータを設定した Item を渡します。（※ `useCsXxxItem` の `Xxx` は Item の種類に応じて異なります。）
「初期化」を使わなかったことに意図はありません。統一性の確認不足でした。
> `useCsXxxItem` というフックを使って初期化した Item を渡します。
こちらに変更しています。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/575247f3ba9ffa35a719b4f9717b6c038686febc

2024-10-25 05:24 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +      stringRule(true, 3, 30)
該当箇所にコードハイライトを入れました。
参考情報のリンクを掲示していただきありがとうございます！

ご指摘いただいた箇所以外にも、必要そうな箇所には適宜コードハイライトを入れています。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/72d66348e36a59865140ae43ac8bdd7c96128b11

2024-10-25 05:24 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/define-validation.md
> +    customValidationRules: buildInCustomValidationRules,
該当箇所にコードハイライトを入れました。

https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/72d66348e36a59865140ae43ac8bdd7c96128b11

2024-10-25 05:29 UTC, MinkToo331 commented
## 1回目レビュー指摘対応時に行った追加対応について

### バリデーションの章構成変更
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/27d5444f042bdbfba5ab6b55ee903fe7cc1f09f4
- 「バリデーションを定義する」と「バリデーションを実施する」に分割
- 「バリデーションを定義する」の中にバリデーションの実行順序に関する解説を追加

### API呼び出しの節について
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/de5675e96bde9ec6c5c8e7dc2aa9a92965ece24a
- 「画面を作る」内での解説をやめ、「CRUD機能を作る」内で解説する方針に変更
- 「本節のゴール」内に、API呼び出し方法について本節では触れないことを明記

2024-10-25 07:27 UTC, tashxii requested changes

2024-10-25 07:27 UTC, tashxii commented on docs/implementation-guide/create-register-screen/execute-validation.md
> +`validationViews` という Props に、バリデーション対象の View の変数を指定します。
ここは、正確には「View の変数の配列を指定します。」だとおもいます。

2024-10-25 07:49 UTC, nagashi84 approved these changes

2024-10-25 08:15 UTC, MinkToo331 commented on docs/implementation-guide/create-register-screen/execute-validation.md
> +`validationViews` という Props に、バリデーション対象の View の変数を指定します。
> `validationViews` という Props に、バリデーション対象の View の変数を配列として指定します。
> 
>   **info**
> `validationViews` には、複数の View 変数を指定することができます。
> `<AxButton validationViews={[view1, view2]}>バリデーション実行</AxButton>`

正確な表現に修正しました。また、複数Viewを指定できることをの説明をINFOに追加しています。
https://github.com/Fintan-contents/dev-react-cs-document/pull/20/commits/b400ee1a19d6b00b5e73833b48c660570bf488ba

2024-10-25 08:40 UTC, tashxii approved these changes

2024-10-25 08:40 UTC, merged