実装ガイド（ボタン・APIイベント）の作成
Fintan-contents/dev-react-cs-document pull request #25
Opened 2024-10-31 11:15 UTC by MinkToo331

2024-11-06 00:18 UTC, tashxii requested changes

2024-11-06 00:18 UTC, tashxii commented on docs/implementation-guide/create-register-screen/difine-api-event.md
ファイル名のtypoがあります。difine -> define です。

2024-11-07 02:33 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/difine-api-event.md
ファイル名のタイピングミスをdifine -> defineに修正しました。

7d49b25cfa723a7370c1aab2039a2343dcd5fd63

2024-11-07 05:32 UTC, akito-miyazaki commented on docs/implementation-guide/create-register-screen/arrange-api-button.md
> +`AxTableLayout` による項目の自動配置の中にイベントは含まれません。イベントに対応するボタンは手動で配置する必要があります。
> 動配置の中にイベントは含まれません

イベントではなくボタンではないでしょうか
5章でイベントを`イベントとは、特定のタイミングやユーザ操作（ボタンクリックなど）によって実行される処理の情報を集約したものです。`と定義しており少し意味がくみ取れないように思います。

2024-11-07 06:02 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/arrange-api-button.md
> +`AxTableLayout` による項目の自動配置の中にイベントは含まれません。イベントに対応するボタンは手動で配置する必要があります。
イベントではなくボタンが正しいため修正しました。
また、文が少し冗長のため
「`AxTableLayout` はItemで定義された入力項目のみ自動配置されるため、ボタンは手動で配置する必要があります。」
に修正しました。

2024-11-07 14:20 UTC, nagashi84 approved these changes

2024-11-08 00:10 UTC, tashxii requested changes

2024-11-08 00:10 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +| `CsMutateLoadEvent` | なし | 必須 | 任意 |
リクエストデータ型が、本当になしでしたか？Mutateなのであると思うのですが。

2024-11-08 00:10 UTC, tashxii commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +  イベントの変数名: useCsXxxEvent(useApiClient()),
いきなりここ1箇所にしか出てこない useApiClient は、分からないと思います。コメントで useApiClientの説明を書くか、カッコ内は文字で説明を書くかしてください。

2024-11-08 00:21 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +| `CsMutateLoadEvent` | なし | 必須 | 任意 |
導入用リポジトリの型定義には
``` tsx
export abstract class CsMutateLoadEvent<
  TApiResponse,
  TApiError = unknown,
> extends CsLoadEvent<TApiResponse, TApiError> {
  abstract start(): void;
}
```
このように記載されていたため、リクエストデータがないと判断しました。

2024-11-08 00:35 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +  イベントの変数名: useCsXxxEvent(useApiClient()),
```tsx
useCsView({
  ...
  イベントの変数名: useCsXxxEvent(useApiClient()), // APIを呼び出すためのクライアント関数（useApiClient()）を指定
})
```

> useApiClient は、分からないと思います。

useApiClient()についての説明がなかったためコメントで説明を加えました。


1bb98b3372dc6b13edfde67b580f70d621391477

2024-11-08 02:36 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +| `CsMutateLoadEvent` | なし | 必須 | 任意 |
追加の修正として
・`CsQueryButtonClickEvent`のレスポンスデータを任意に修正
・LoadEventとButtonClickEventにQuery、Mutateの違いを説明する文章の追加
を行いました。
ご確認をお願いいたします。

2024-11-08 02:46 UTC, RenTakemoto-10157 commented on docs/implementation-guide/create-register-screen/define-api-event.md
> +  イベントの変数名: useCsXxxEvent(useApiClient()),
`useCsXxxEvent`の引数に日本語の説明をそのまま入れる形に修正しました。

2024-11-08 07:19 UTC, tashxii approved these changes

2024-11-08 07:19 UTC, merged