主要なAPIリファレンスの作成
Fintan-contents/dev-react-cs-document pull request #26
Opened 2024-11-06 06:07 UTC by RenTakemoto-10157

2024-11-22 00:29 UTC, tashxii requested changes

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +`stringCustomValidationRule` は、指定されたバリデータとエラーメッセージを使用して、テキスト入力項目に対するカスタムバリデーションルールを生成します。[useCsView](../screen-define/useCsView.md)の`options`で使用できます。
> [useCsView](../screen-define/useCsView.md)の`options`で使用できます

ここでの説明は不要です。また、言葉足らずなので説明になっていません。消してください。

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +\*1：`CustomValidator`は バリデーションエラーが発生したかどうかを検証する型定義です。
> バリデーションエラーが発生したかどうかを検証する型定義

説明が正確でありません。

```
バリデーション処理の際にコールバックされるtrue/falseを返す関数の型定義です。
エラーの際は、falseを返すよう実装します。
コールバックの引数には、検証する値のnewValueと検証対象のitemが渡されます。
```

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +\*2：`CustomValidateMessage`はバリデーションエラーが発生した際のエラーメッセージを出力する型定義です。
こちらも説明が足りません。
```
バリデーションエラーが発生した際のエラーメッセージを作成するコールバック関数の型定義です。
コールバックの引数には、項目のlabel、検証した値のnewValue、検証対象のitemが渡されます。
```

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +| validator | 〇   | `CustomValidator<string>*¹`       | 入力値を検証するためのバリデータを指定します。正規表現を用いてバリデーションを実施したい場合は、`createRegExpValidator`を使用することで指定できます。 |
> 正規表現を用いてバリデーションを実施したい場合は、`createRegExpValidator`を使用することで指定できます。

「使用することで指定できます」という言葉はおかしいです。

```
正規表現を用いてバリデーションを実施したい場合は、`createRegExpValidator` というヘルパ関数で簡潔に実装することができます。詳しくは使用例を参照ください。
```

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/event-definition-hook/useCsRqAdvancedMutateButtonClickEvent.md
> +`useCsRqAdvancedMutateButtonClickEvent` は、Axios（シンプル版）もしくは React Query に対応する更新系 API ボタンイベントを初期化するためのフックです。
> Axios（シンプル版）

この単語は今まで使われていないですし、拡張版の話です。

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/helper-function/stringRule.md
> +`stringRule` は、文字列入力項目に対するバリデーションルールを生成するための関数です。必須項目、最小・最大文字数、カスタムルールを設定できます。
「必須項目」ではなく、「必須項目かどうか」
「設定」ではなく「指定」です

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/helper-function/useInit.md
> +入力項目の初期値と更新関数を持った`StateResult<T>`を返します。
StateResultの説明がないです。

2024-11-22 00:29 UTC, tashxii commented on docs/reference/api-reference/items-definition-hook/useCsInputTextItem.md
> +`useCsInputTextItem` は、`AxInputText`に対応する Item を初期化するためのフックです。
`AxInputText`を出さなくて良いですし、説明になっていません。
「テキストボックスに対応するItem」と書けば良いです

2024-11-25 11:19 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +`stringCustomValidationRule` は、指定されたバリデータとエラーメッセージを使用して、テキスト入力項目に対するカスタムバリデーションルールを生成します。[useCsView](../screen-define/useCsView.md)の`options`で使用できます。
この節での説明は不要であったため削除しました。

2024-11-25 11:21 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +\*1：`CustomValidator`は バリデーションエラーが発生したかどうかを検証する型定義です。
以下のように文章を修正しました。
*1：`CustomValidator`は バリデート関数で、以下の定義になります。

```ts
type CustomValidator<T> = (newValue: T | undefined, item: CsItem<T>) => boolean;
````

またバリデート関数の説明を追加しました。
> バリデート関数とは、バリデーション処理の際に呼び出されるコールバック関数で、エラーとしたいときに `false` を返すよう実装します。コールバックの引数は、検証する値の `newValue` と検証対象の `item` が渡されます。

2024-11-25 11:23 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +\*2：`CustomValidateMessage`はバリデーションエラーが発生した際のエラーメッセージを出力する型定義です。
以下のように文章を修正しました。
*2：`CustomValidateMessage`はメッセージ関数で、以下の定義になります。

```ts
type CustomValidateMessage<T> =
  | ((label: string, value: T, item: CsItem<T>) => string)
  | string;
```

またメッセージ関数の説明を追加しました。
> メッセージ関数とは、バリデーション処理がエラーとなった際に呼び出されるコールバック関数で、メッセージを文字列として返すよう実装します。コールバックの引数は、項目の `label`、検証した値の `value`、検証対象の `item` が渡されます。

2024-11-25 11:25 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/helper-function/stringRule.md
> +`stringRule` は、文字列入力項目に対するバリデーションルールを生成するための関数です。必須項目、最小・最大文字数、カスタムルールを設定できます。
> 「必須項目」ではなく、「必須項目かどうか」

「必須項目」だけでは言葉足らずのため「必須項目かどうか」に修正しました。

> 「設定」ではなく「指定」です

文脈的に指定の方が正しいため、「指定」に修正しました。

2024-11-25 11:26 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/event-definition-hook/useCsRqAdvancedMutateButtonClickEvent.md
> +`useCsRqAdvancedMutateButtonClickEvent` は、Axios（シンプル版）もしくは React Query に対応する更新系 API ボタンイベントを初期化するためのフックです。
「Axios（シンプル版）」ではなく、「Orval（拡張版）」に修正しました。

2024-11-25 11:28 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/helper-function/useInit.md
> +入力項目の初期値と更新関数を持った`StateResult<T>`を返します。
>StateResultの説明がないです。

文章の初めにuseInitの説明を追加しました。
`useInit` は、入力項目の初期値を設定するためのフックです。このフックは[入力項目定義のフック](../../../category/入力項目定義のフック)にある`useCsXxxItem`で使用されます。内部実装は以下のようになっており、型引数 `T` および `undefined` を状態として返します。

2024-11-25 11:29 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/items-definition-hook/useCsInputTextItem.md
> +`useCsInputTextItem` は、`AxInputText`に対応する Item を初期化するためのフックです。
「テキストボックスに対応するItem」に修正しました。

2024-11-25 11:31 UTC, RenTakemoto-10157 commented on docs/reference/api-reference/custom-validation-definition-function/stringCustomValidationRule.md
> +| validator | 〇   | `CustomValidator<string>*¹`       | 入力値を検証するためのバリデータを指定します。正規表現を用いてバリデーションを実施したい場合は、`createRegExpValidator`を使用することで指定できます。 |
日本語が正しくなかったため、「～で簡潔に実装することができます」に修正しました。
また、説明文も修正しました。

2024-11-26 00:03 UTC, tashxii approved these changes

2024-11-26 00:03 UTC, merged