[
Fintan-contents/dev-react-cs-document pull request #28
Opened 2024-11-07 07:42 UTC by RenTakemoto-10157

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +更新機能のイベントの型定義には`CsMutateButtonClickEvent`を指定します。更新用の View（`TodoEditView`）の型にイベントの型を定義します。型パラメータには API リクエスト、API レスポンス型を指定します。
細かいですが、
>API リクエスト、API レスポンス型

更新APIのリクエスト、レスポンスの型の方がしっくりきます。

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +更新機能のイベントの型定義には`CsMutateButtonClickEvent`を指定します。更新用の View（`TodoEditView`）の型にイベントの型を定義します。型パラメータには API リクエスト、API レスポンス型を指定します。
>更新用のViewの型にイベントの型定義を指定します。

Viewの型ではなくプロパティではないでしょうか

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +`app/todo/page.view.ts`ファイルで以下のようなコードを記述します。
>`app/todo/page.view.ts`ファイルで以下のようなコードを記述します。

具体的な実装をいかに示します。
でいい気がしました。
コードブロックの上部にファイル名も記載されていますし。

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +    // 更新対象のId、APIのレスポンスデータ型を定義
リクエストではないでしょうか

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +更新用の View（`TodoEditView`）の初期化にイベントの初期化処理を追加します。更新 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`useEditUserInfo()`を指定します。
Todoアプリの更新APIって`useEditUserInfo()`でしたっけ

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +      todoPutView.id.setValue(record?.id);
急に出てきたrecordに対してコメントで説明があった方が親切なように思いました
更新対象の現在の値など

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +更新 API に対応する`AxMutateButton`を配置します。`event`引数にはボタン押下時に実施したいイベント（`updateButton`）を指定します。`validationViews`にはバリデーションを実施したい画面単位（`todoEditView`）を配列型で指定します。
更新APIに対応するというよりEventの型に対応するボタンではないでしょうか。

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +以上の実装により、更新機能 の実装が完了します。ボタン押下時に適切に更新 API が呼び出されているか確認してください。
> 以上の実装により、更新機能 の実装が完了します。

冗長な説明になっている気がします。
以上で、更新機能の実装が完了します。
で十分な気がします。

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +todoEditView.updateButton.setRequest({
これを`page.tsx`のどこに実装するかという情報が個人的にはほしいと感じました。
初めて実装した際onClickに実装してしまいましたが違いますよね・・？
同じような間違いをする人がおそらくいそうなので

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +固定の文字列などを用いて View に初期値を渡すには`useInit`を指定します。ただし、取得 API のような非同期で取得される値を渡す場合には`setValue`を使用します。
`useInit`**で**指定します。の方がしっくりきます。

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +固定の文字列などを用いて View に初期値を渡すには`useInit`を指定します。ただし、取得 API のような非同期で取得される値を渡す場合には`setValue`を使用します。
知識が浅い故の質問です！
Viewに初期値を渡すんですか？Itemではなくて？

2024-11-07 09:10 UTC, akito-miyazaki commented on docs/implementation-guide/crud/goal.md
> +API の実装方法にフォーカスした説明を行うため、API を含めた一通りの画面実装を行いたい場合は[画面を作る](../create-register-screen/)を参照してください。
APIの実装ではないと思います。
APIの呼び出し方（これはちょっと言い方あれだけど）では？

2024-11-07 09:12 UTC, akito-miyazaki commented on docs/implementation-guide/crud/update-feature.md
> +更新 API に対応する`AxMutateButton`を配置します。`event`引数にはボタン押下時に実施したいイベント（`updateButton`）を指定します。`validationViews`にはバリデーションを実施したい画面単位（`todoEditView`）を配列型で指定します。
この指摘的外れな気がしてきました。
が、考えについて返信ほしいです。

2024-11-08 03:51 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +`app/todo/page.view.ts`ファイルで以下のようなコードを記述します。
そもそもの文言が不要なため削除しました。

8ebb2fbeed12cdbf4e55f9a065f0a64ba16a8049

2024-11-08 03:53 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +更新用の View（`TodoEditView`）の初期化にイベントの初期化処理を追加します。更新 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`useEditUserInfo()`を指定します。
間違っていたため、`usePostTodo()`に修正しました。

acc37b92439f2d77e6e261b90d7a2ddd4bfc7893

2024-11-08 03:53 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +    // 更新対象のId、APIのレスポンスデータ型を定義
リクエストに修正しました。

47a2f1a3e3dda4b5bee420bdc9d74c895468cfd4

2024-11-08 03:54 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +更新機能のイベントの型定義には`CsMutateButtonClickEvent`を指定します。更新用の View（`TodoEditView`）の型にイベントの型を定義します。型パラメータには API リクエスト、API レスポンス型を指定します。
>更新APIのリクエスト、レスポンスの型の方がしっくりきます。
>Viewの型ではなくプロパティではないでしょうか

上記の文言に修正しました。

47a2f1a3e3dda4b5bee420bdc9d74c895468cfd4

2024-11-08 04:04 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +固定の文字列などを用いて View に初期値を渡すには`useInit`を指定します。ただし、取得 API のような非同期で取得される値を渡す場合には`setValue`を使用します。
Itemが正しいため「入力項目に初期値を渡す」に修正しました。

47a2f1a3e3dda4b5bee420bdc9d74c895468cfd4

2024-11-08 04:08 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +以上の実装により、更新機能 の実装が完了します。ボタン押下時に適切に更新 API が呼び出されているか確認してください。
上記の文章で修正しました。

47a2f1a3e3dda4b5bee420bdc9d74c895468cfd4

2024-11-08 04:09 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/goal.md
> +API の実装方法にフォーカスした説明を行うため、API を含めた一通りの画面実装を行いたい場合は[画面を作る](../create-register-screen/)を参照してください。
「本節では各機能の API 呼び出し方法にフォーカスして説明します」に修正しました。

2afa5006e55699487755a8f30bf8d1762ab0b310

2024-11-08 07:27 UTC, tashxii requested changes

2024-11-08 07:27 UTC, tashxii commented on docs/implementation-guide/crud/update-feature.md
> +更新用の View（`TodoEditView`）の初期化にイベントの初期化処理を追加します。更新 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`usePutTodo()`を指定します。
2回初期化と出ていて文章が変に見えます。

> 更新用の View（`TodoEditView`）『の初期化』にイベントの初期化処理を追加します

以下のような文で良いとおもいます。
```
更新用の View（`TodoEditView`）にイベントの初期化処理を追加します
```

2024-11-08 08:29 UTC, RenTakemoto-10157 commented on docs/implementation-guide/crud/update-feature.md
> +更新用の View（`TodoEditView`）の初期化にイベントの初期化処理を追加します。更新 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`usePutTodo()`を指定します。
> 更新用の View（`TodoEditView`）にイベントの初期化処理を追加します

冗長な文章になっていたため、上記の文章に修正しました。

f670f5031733c0d5c99bfb72499522e4f7115be6

2024-11-08 08:37 UTC, RenTakemoto-10157 commented
今回Orvalの拡張版を使用しているため、それを伝える文章を「本節の内容」に記載しました。（それに伴いEventのフックの記述にミスがあったので修正しています。）合わせてご確認をお願いいたします。

8b81fd71deb463a31e739b70a7b8d2d07c1100e3
097165ab94fabf5d1eb19583e7bc8b24af1c55c2

2024-11-12 23:57 UTC, tashxii approved these changes

2024-11-12 23:58 UTC, merged