【CRUD】登録/削除ページ作成
Fintan-contents/dev-react-cs-document pull request #32
Opened 2024-11-14 06:00 UTC by akito-miyazaki

## 概要
CRUDの登録/削除ページを作成しました。

## 動作確認
`npm run start`で起動。
〇登録機能ページ
実装ガイド>CRUD機能を作る>登録機能
〇削除機能ページ
実装ガイド>CRUD機能を作る>削除機能

 ## 申し送り事項
特にございません。

2024-11-18 04:39 UTC, tashxii requested changes

2024-11-18 04:39 UTC, tashxii commented on docs/implementation-guide/crud/create-feature.md
> +本節ではいかに示すような登録機能の実装方法について説明します。
「いか」→「以下」のほうが良いかと。

2024-11-18 04:39 UTC, tashxii commented on docs/implementation-guide/crud/create-feature.md
> +登録用の View（`TodoCreateView`）にイベントの初期化処理を追加します。登録 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`usePostTodo()`を指定します。
下は、RqAdvancedになっているので、整合性が取れていません。コードのRqAdvancedに合わせたほうが良いでしょう。

2024-11-18 04:39 UTC, tashxii commented on docs/implementation-guide/crud/delete-feature.md
> +    setIsOpenDeleteModal();
setIsOpenDeleteModal(false);ではないでしょうか？

2024-11-18 04:39 UTC, tashxii commented on docs/implementation-guide/crud/delete-feature.md
> +        setIsOpenDeleteModal();
ここも、setIsOpenDeleteModal(false);ではないでしょうか？

2024-11-18 06:55 UTC, akito-miyazaki commented on docs/implementation-guide/crud/create-feature.md
> +本節ではいかに示すような登録機能の実装方法について説明します。
他ページと統一性を持たせるため「以下」に修正しました。
731a6441bfd24ab09bde3d81cbb3e08a0aee4ab6

2024-11-18 06:56 UTC, akito-miyazaki commented on docs/implementation-guide/crud/create-feature.md
> +登録用の View（`TodoCreateView`）にイベントの初期化処理を追加します。登録 API では Event のフックに`useCsRqMutateButtonClickEvent()`、引数には Orval で自動生成された API フック`usePostTodo()`を指定します。
`useCsRqAdvancedMutateButtonClickEvent`に修正しました。
4dff44e8c485ea82a5df3edfb59aa10e1d7da64b

2024-11-18 08:12 UTC, akito-miyazaki commented on docs/implementation-guide/crud/delete-feature.md
> +    setIsOpenDeleteModal();
page側でStateを管理しておりModalにはfalseにセットする関数を渡しているため引数には何も渡していません。
しかしそれだけでは不十分だと感じたためコメントを追記しました。
557032acc531279ecf6caed6e2f32a857bce50e6

2024-11-18 08:13 UTC, akito-miyazaki commented on docs/implementation-guide/crud/delete-feature.md
> +        setIsOpenDeleteModal();
https://github.com/Fintan-contents/dev-react-cs-document/pull/32#discussion_r1846056333
上記と同様です。

2024-11-20 01:48 UTC, tashxii commented on docs/implementation-guide/crud/delete-feature.md
> +    setIsOpenDeleteModal();
「falseにセットする関数」の名前がsetIsOpenDeleteModalなのはわかりにくいです。
理由は、その関数名からはReactのuseStateの変数宣言の慣習から以下のようなものを想像してしまうからです。
```
const [isOpenDeleteModal, setIsOpenDeleteModal] = useState(false);
```
関数名を closeDeleteModal(); のようにするほうがわかりやすいとおもいます。

2024-11-20 05:21 UTC, akito-miyazaki commented on docs/implementation-guide/crud/delete-feature.md
> +    setIsOpenDeleteModal();
SetIsOpenDeleteModdalを渡して明示的にfalseをセットするように修正しました。
ae355b35cec5a502edd53c22d044f1b124c7a377
サンプルアプリも同様な修正を加えたため後程PR作成します。

2024-11-20 05:22 UTC, akito-miyazaki commented on docs/implementation-guide/crud/delete-feature.md
> +        setIsOpenDeleteModal();
https://github.com/Fintan-contents/dev-react-cs-document/pull/32#discussion_r1849550093
同様です

2024-11-22 00:55 UTC, tashxii approved these changes

2024-11-22 00:55 UTC, merged