【CRUD】取得/検索ページ作成
Fintan-contents/dev-react-cs-document pull request #34
Opened 2024-11-15 01:01 UTC by akito-miyazaki

## 概要
CRUDの取得/検索ページを作成しました。

## 動作確認
`npm run start`で起動。
〇登録機能ページ
実装ガイド>CRUD機能を作る>取得機能
〇削除機能ページ
実装ガイド>CRUD機能を作る>検索機能

 ## 申し送り事項
サンプルアプリに合わせてprettierでコード整形しました。
そのため`create-update.md`,`goal.md`に差分が出ています。

2024-11-18 04:47 UTC, tashxii requested changes

2024-11-18 04:47 UTC, tashxii commented on docs/implementation-guide/crud/search-feature.md
> +        { assignee_eq: assignee }, // クエリパラメータを指定
ここは、 `assignee.value ?? ""` になると思います。

2024-11-18 04:47 UTC, tashxii commented on docs/implementation-guide/crud/search-feature.md
> +  searchTodo: CsQueryButtonClickEvent<ListTodoResponse>;
他のイベントはxxxButtonとなっているので、`searchTodo` より `searchButton` とするほうが良いとおもいます。直す際は、全部で４箇所あったので注意してください。

2024-11-18 08:21 UTC, akito-miyazaki commented on docs/implementation-guide/crud/search-feature.md
> +        { assignee_eq: assignee }, // クエリパラメータを指定
ご指摘いただきました通り修正しました。
33cdbd550f69197a4b30751d015405aaeb5d3494

2024-11-18 08:21 UTC, akito-miyazaki commented on docs/implementation-guide/crud/search-feature.md
> +  searchTodo: CsQueryButtonClickEvent<ListTodoResponse>;
Buttonで統一するように修正しました。
3c59b333b1eabd04f5b1c534ad610758d918e4e0

2024-11-18 08:22 UTC, akito-miyazaki commented on docs/implementation-guide/crud/search-feature.md
> +  searchTodo: CsQueryButtonClickEvent<ListTodoResponse>;
サンプルアプリに対しても同様の修正をいたします。
後程PR作成します。

2024-11-22 00:58 UTC, tashxii approved these changes

2024-11-22 00:59 UTC, merged