「はじめに」の作成
Fintan-contents/dev-react-cs-document pull request #5
Opened 2024-08-26 04:42 UTC by MinkToo331

レビューよろしくお願いいたします。

レビュー準備が完了しているもの

- 全体構成
- 文章の内容
- GIFに含めるシーンの概要
　- 項目を追加する操作 (#画面項目定義、#バリデーション定義)
　- バリデーションを実行する操作 (#高機能なボタン)

残作業

- GIFの撮り直し
　- 項目名の修正を反映させる
　- 特徴の説明にマッチしたシーンにする　 　

2024-08-26 23:13 UTC, t-shimoda requested changes

2024-08-26 23:13 UTC, t-shimoda commented on docs/intro.md
> +省力化コンポーネントは、従来の React 開発におけるコードの冗長さを排除し、開発効率を向上させるための強力なツールです。
ツールではなく、ライブラリという表現のほうが良いでしょう。
ツールだとエディタやなにかを想像させるためです。

2024-08-26 23:13 UTC, t-shimoda commented on docs/intro.md
> +  - バリデーションルールをパラメータとして渡すだけでスキーマが自動生成されるため、実装者が定型のバリデーションスキーマを記述する必要がなくなります。
バリデーションスキーマの自動生成は内部の動作の話で、読者にとって興味ないところになるので、省略して、
「バリデーションルールをパラメータとして渡すだけで定義できます」
くらいにしたほうが良いと思います。

2024-08-26 23:13 UTC, t-shimoda commented on docs/intro.md
> +上のデモは、省力化コンポーネントが備える次の 3 つの特徴を示すものです。
自動レイアウトに触れていないので、ここでは「3つ」と限定せずに、「次の特徴を示すものです」として、
「1つの画面内の複数のコンポーネントを自動レイアウトで配置できます」のような特徴を追加してください。

2024-08-26 23:13 UTC, t-shimoda commented on docs/intro.md
> +上記 3 つの特徴を持つ省力化コンポーネントを用いた場合、従来手法の<strong> 約 30% ～ 40%</strong>のコード量で同様の画面を実装することができます。冗長なコードを排除することにより、<u>開発生産性の向上</u>および<u>メンテナンス性の高いコードベースの維持</u>が可能となります。
ここも、3つと限定せずに、「上記のような特徴を持つ」としたほうが良いでしょう。

2024-08-27 01:26 UTC, nagashi84 commented on docs/intro.md
> +このコンテンツでは、 React で画面開発を行う際の生産性を向上させる[省力化コンポーネント](省力化コンポーネントを知るへのリンク)について解説します。
`生産性の向上` だけ書いているけど、最後のまとめで以下のようにしているので、メンテナンス性も高くなることを書くといいかなと思いました。

> 開発生産性の向上およびメンテナンス性の高いコードベースの維持

2024-08-27 02:46 UTC, MinkToo331 commented on docs/intro.md
> +上記 3 つの特徴を持つ省力化コンポーネントを用いた場合、従来手法の<strong> 約 30% ～ 40%</strong>のコード量で同様の画面を実装することができます。冗長なコードを排除することにより、<u>開発生産性の向上</u>および<u>メンテナンス性の高いコードベースの維持</u>が可能となります。
(下田さんより追加指摘)
コード量削減の図も載せる←約30%~40%削減が視覚的に分かるように

2024-08-27 05:37 UTC, MinkToo331 commented on docs/intro.md
> +省力化コンポーネントは、従来の React 開発におけるコードの冗長さを排除し、開発効率を向上させるための強力なツールです。
ツールをライブラリに変更しました。

2024-08-27 05:40 UTC, MinkToo331 commented on docs/intro.md
> +  - バリデーションルールをパラメータとして渡すだけでスキーマが自動生成されるため、実装者が定型のバリデーションスキーマを記述する必要がなくなります。
スキーマ自動生成の話を無くし、「ルールをパラメータとして渡すだけでバリデーションが定義できます。」にしました。

2024-08-27 05:42 UTC, MinkToo331 commented on docs/intro.md
> +上のデモは、省力化コンポーネントが備える次の 3 つの特徴を示すものです。
特徴「自動レイアウト制御機能が使える」を追加しました。

2024-08-27 05:43 UTC, MinkToo331 commented on docs/intro.md
> +上記 3 つの特徴を持つ省力化コンポーネントを用いた場合、従来手法の<strong> 約 30% ～ 40%</strong>のコード量で同様の画面を実装することができます。冗長なコードを排除することにより、<u>開発生産性の向上</u>および<u>メンテナンス性の高いコードベースの維持</u>が可能となります。
「上記のような特徴を持つ」としました。

2024-08-27 05:46 UTC, MinkToo331 commented on docs/intro.md
> +このコンテンツでは、 React で画面開発を行う際の生産性を向上させる[省力化コンポーネント](省力化コンポーネントを知るへのリンク)について解説します。
「このコンテンツでは、 React で画面開発を行う際の生産性とメンテナンス性を向上させる省力化コンポーネントについて解説します。」という内容にし、メンテナンス性についても触れるようにしました。

2024-08-27 08:43 UTC, MinkToo331 commented on docs/intro.md
> +上記 3 つの特徴を持つ省力化コンポーネントを用いた場合、従来手法の<strong> 約 30% ～ 40%</strong>のコード量で同様の画面を実装することができます。冗長なコードを排除することにより、<u>開発生産性の向上</u>および<u>メンテナンス性の高いコードベースの維持</u>が可能となります。
コード量削減の図をinformationとして載せました。

2024-08-28 04:23 UTC, merged