「省力化コンポーネントを知る > モチベーション」の内容作成
Fintan-contents/dev-react-cs-document pull request #6
Opened 2024-08-26 10:39 UTC by MinkToo331

レビューよろしくお願いいたします。

レビュー準備が完了しているもの

- 全体構成
- 文章の内容
- ソースコード

残作業
- 特になし

2024-08-26 23:23 UTC, t-shimoda requested changes

2024-08-26 23:23 UTC, t-shimoda commented on docs/know-cs-component/motivation.md
> +const onChangeSex = (e: RadioChangeEvent) => {
性別は、Genderとしたほうがよいです。生物的な性別(Sex)ではなく、社会的な性別という意味になります

2024-08-26 23:23 UTC, t-shimoda commented on docs/know-cs-component/motivation.md
> +const validationSchema = {
yupを使った例にしてください。また、「ここでは、yupを使ったコード例を示しています」という補足もつけましょう。

2024-08-26 23:23 UTC, t-shimoda commented on docs/know-cs-component/motivation.md
> +// ボタン押下時に実行されるコールバック関数
コード例が正確ではないのと、ハンドラ一つを渡しているだけにしか見えないので、
ボタン外部でのスピナの表示やメッセージの表示を具体的に書いてください。

2024-08-26 23:23 UTC, t-shimoda commented on docs/know-cs-component/motivation.md
> +1. 分散して記述される入力項目の定義
順番はあまり意味がないので、数字の箇条書きではなく、同等の列挙を表す通常の「中点」での箇条書きにしたほうがよいと思います。番号での参照をするわけでもないはずですので。

2024-08-27 01:49 UTC, nagashi84 commented on docs/know-cs-component/motivation.md
> +一般的な入力項目には、ラベルやバリデーションメッセージの表示領域が必要です。しかし、これらを毎回実装者が個別に記述するのは手間がかかり、コードの冗長さを引き起こします。
ラベル、項目、メッセージの配置を調整するのも結構大変だし、統一を図るのは難しいところだと思います。

2024-08-27 09:10 UTC, MinkToo331 commented on docs/know-cs-component/motivation.md
> +const onChangeSex = (e: RadioChangeEvent) => {
ドキュメント内の変数名をgenderに変更しました。
danmachiの変数名変更対応は別タスクとして行います。

2024-08-27 09:25 UTC, MinkToo331 commented on docs/know-cs-component/motivation.md
> +const validationSchema = {
yupを使った例に変更しました。
「ここでは、yupを使ったコード例を示しています」というニュアンスの文章も追加しています。

2024-08-27 09:29 UTC, MinkToo331 commented on docs/know-cs-component/motivation.md
> +1. 分散して記述される入力項目の定義
「中点」での箇条書きに変更しています

2024-08-28 00:36 UTC, MinkToo331 commented on docs/know-cs-component/motivation.md
> +一般的な入力項目には、ラベルやバリデーションメッセージの表示領域が必要です。しかし、これらを毎回実装者が個別に記述するのは手間がかかり、コードの冗長さを引き起こします。
画面内でスタイルを統一しなければならないことの難しさについても、説明＆コードに追加しました。

2024-08-28 01:39 UTC, MinkToo331 commented on docs/know-cs-component/motivation.md
> +// ボタン押下時に実行されるコールバック関数
コード例をより具体的な内容に変更しました。

2024-08-28 04:45 UTC, tashxii approved these changes

2024-08-28 04:46 UTC, merged