「省力化コンポーネントを知る>特徴
Fintan-contents/dev-react-cs-document pull request #7
Opened 2024-08-27 09:08 UTC by RenTakemoto-10157

2024-08-27 23:42 UTC, t-shimoda requested changes

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +    sex: useCsRadioBoxItem("性別", useInit(""), stringRule(true),
入力フォームの性別はGender＝社会的な性別が自然です。

同様の指摘をしています。他のPRとレビューも見るようにしましょう
https://github.com/Fintan-contents/dev-react-cs-document/pull/6#discussion_r1731928562

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +- <strong>自動レイアウト制御機能が使える</strong>
自動レイアウト機能とだけで、制御は不要可と思います

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +export const ConceptApplyedPane: React.FC = () => {
例が全部「ConceptApplyedPane」となっているのは変です。
画面項目の文脈によって適切なコンポーネント名（RegisterUserComponent, PostTodoComponentのような名前）にするか、「SampleComponent」のような例とわかりやすい名前に統一するかです。前者のほうがより良いでしょう。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +また、文字列型以外にも数値型のバリデーションや文字列型など多様なバリデーションルールを定義することもできます。
「また文字列型以外にも数値型のバリデーションや文字列型など多様なバリデーションルールを対応する関数`numberRule`や`stringArrayRule`などを使って定義することもできます」としたほうがより具体的です。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +さらに、カスタムバリデーションルールを用いると「半角数字」や「全角カナ」など、より詳細なバリデーションを定義することも可能です。これにより、アプリケーション固有の要件に合わせた柔軟なバリデーションが実現できます。
１行で良いので、カスタムバリデーションルールを指定したサンプルコードもこの下に載せて上げてください。
「この例のように、stringRuleや他のルール関数の省略可能な四番目の引数としてカスタムバリデーションルールの名前を指定します。」と補足するとよいでしょう。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +API 呼び出しの結果やバリデーションエラーなどの情報をユーザーに伝えることができます。これにより、ユーザーは次に何をすべきかを直感的に理解できます。メッセージをボタンに渡すことで実装することができます。
「ボタン押下後に、メッセージやエラーメッセージを通知することが必要な場合は、メッセージ表示機能を使います。メッセージ表示機能ではAPI 呼び出しの結果やバリデーションエラーなどの情報...」としたほうが良いでしょう。

「これにより、ユーザーは次に何をすべきかを直感的に理解できます」は要らないです。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +export const useTodosPostView = (): TodosPostView => {
↑が、RegisterUserViewという名前なので、PostTodosViewと対応を取るべきです。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +<AxMutateButton event={view.createButton} validationViews={[view]} successMessage="API送信が成功しました。">
例としてリッチになるよう、エラーメッセージも指定するようにしてください。

また、「API送信が成功しました」は例として相応しくないので、成功メッセージは「Todoを追加しました」、失敗メッセージは「Todoの追加に失敗しました」としてください。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> + `colSize`に数値型を指定することで、指定した数値ごとに項目を並べることができます。
「view」の指定が抜けているので、
・`view`にレイアウトに並べたい画面項目を含むビューを指定します。
・`colSize`に数値型を指定することで...
とviewも説明してください。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +自動レイアウトにより、開発者はレイアウトを調整する必要がなくなり、他のタスクにリソースを割くことができます。また、ユーザーは自然な流れで操作を行うことができ、必要な情報や機能に迅速にアクセスできます。
「他のタスクにリソースを割くことができます。また、ユーザーは自然な流れで操作を行うことができ、必要な情報や機能に迅速にアクセスできます。」不要です。主観的な表現や余計なお世話である内容です。
「～の場合は、自動レイアウト機能が利用できます」のような構文にすべきです。

具体的には、「画面項目の並びが単純で機械的なレイアウトでよい場合は、自動レイアウト機能が利用できます。画面項目の並びが複雑な場合やデザインを重視する場合は手動でレイアウトします。」です

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +ボタンの特徴については以下の通りです。
「ボタンの特徴については以下の通りです。
いずれの機能も従来はボタンの外部やハンドラ内で実装していた処理が内部に組み込まれており、パラメータを渡すだけで簡単に利用できます。」
と全体の説明を入れたほうがより良くなります。

2024-08-27 23:42 UTC, t-shimoda commented on docs/know-cs-component/features.md
> +};
コンポーネントが閉じているので、Viewの定義だけになっています。１行で良いのでAxLayoutを追加するか、中略するかです。前者のほうがわかりやすいかと思っています。

2024-08-28 01:10 UTC, nagashi84 commented
画像のボタン名が「バリデーションテスト」となっているところが気になりました。
デモアプリとしてはAPI実行しないかもしれないですが、「登録」などにしておくべきかと思います。

2024-08-28 01:17 UTC, nagashi84 commented on static/img/automatic-layout.png
画像のボタン名が「バリデーションテスト」となっているところが気になりました。
デモアプリとしてはAPI実行しないかもしれないですが、「登録」などにしておくべきかと思います。

2024-08-28 01:17 UTC, nagashi84 commented on docs/know-cs-component/features.md
> +  post
ボタンのラベルを `post` にすることは無いと思うので、適切なものに変えましょう。
Todo のサンプルなら `追加` とか `add` とかかな

2024-08-28 08:51 UTC, RenTakemoto-10157 commented on static/img/automatic-layout.png
画像のボタン名を「登録」に変更しました。

2024-08-29 01:11 UTC, merged